AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  s3forhw3photo:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3forhw3photo
  hw3lf2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hw3lf2
      Handler: hw3lf2.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda_functions
      Description: 'Lambda function 2 in hw3'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::973649192514:role/LF-admin'
      Environment:
        Variables:
          REGION: us-east-1
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /search
            Method: get
        putAZsAPI:
          Type: Api
          Properties:
            Path: /upload
            Method: put
  hw3lf1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: hw3lf1
      Handler: hw3lf1.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda_functions
      Description: 'Lambda function 1 in hw3'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::973649192514:role/LF-admin'
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket:
              Ref: s3forhw3photo
            Events: s3:ObjectCreated:Put
      Environment:
        Variables:
          REGION: us-east-1